### ISSUE TITLE
req: play wave file when stock detected

### ISSUE THREAD

**Issue by rugabunda** [LesterLyu/where-to-buy-3080#2]
excellent job! this is a very tight and efficient web scraper.. thank you for sharing this! 

If you would add some code to play a sound file when eligible stock detected, that would be very useful! Thanks

**Comment by LesterLyu** [comment]
Turn on notification sound on your computer.

**Comment by rugabunda** [comment]
> 
> 
> Turn on notification sound on your computer.

what sound notification? where is this?

**Comment by rugabunda** [comment]
> 
> 
> > Turn on notification sound on your computer.
> 
> what sound notification? where is this?

how do we enable sound notifications in linux?

**Comment by rugabunda** [comment]
the instructions in the readme files are wayyyy too complicated for the laymen, it should be as simple switch you can enable

**Comment by rugabunda** [comment]
i am using lubuntu 20.10

**Comment by rugabunda** [comment]
Seems like these instructions are built for java coders. You suggest fallbacks are defined in "DECISION_FLOW.md", but there is no file called DECISION_FLOW.md' in yoru git.  Please explain why. You also mention java code here, but you don't explain which files to insert this code. Do I place it in a random directory under /var/tmp/3093420?

```
## Cross-Platform Advanced Usage

Standard usage, with cross-platform fallbacks as defined in the
[reporter flow chart](./DECISION_FLOW.md). All of the options
below will work in some way or another on most platforms.

```javascript
const notifier = require('node-notifier');
const path = require('path');

notifier.notify(
  {
    title: 'My awesome title',
    message: 'Hello from node, Mr. User!',
    icon: path.join(__dirname, 'coulson.jpg'), // Absolute path (doesn't work on balloons)
    sound: true, // Only Notification Center or Windows Toasters
    wait: true // Wait with callback, until user action is taken against notification, does not apply to Windows Toasters as they always wait or notify-send as it does not support the wait option
  },
  function (err, response) {
    // Response is response from notification
  }
);

notifier.on('click', function (notifierObject, options, event) {
  // Triggers if `wait: true` and user clicks notification
});

notifier.on('timeout', function (notifierObject, options) {
  // Triggers if `wait: true` and notification closes
});
```

If you want super fine-grained control, you can customize each reporter individually,
allowing you to tune specific options for different systems.

See below for documentation on each reporter.

**Example:**

```javascript
const NotificationCenter = require('node-notifier/notifiers/notificationcenter');
new NotificationCenter(options).notify();

const NotifySend = require('node-notifier/notifiers/notifysend');
new NotifySend(options).notify();

const WindowsToaster = require('node-notifier/notifiers/toaster');
new WindowsToaster(options).notify();

const Growl = require('node-notifier/notifiers/growl');
new Growl(options).notify();

const WindowsBalloon = require('node-notifier/notifiers/balloon');
new WindowsBalloon(options).notify();
```

Or, if you are using several reporters (or you're lazy):

```javascript
// NOTE: Technically, this takes longer to require
const nn = require('node-notifier');

new nn.NotificationCenter(options).notify();
new nn.NotifySend(options).notify();
new nn.WindowsToaster(options).notify(options);
new nn.WindowsBalloon(options).notify(options);
new nn.Growl(options).notify(options);
```

```

**Comment by rugabunda** [comment]
tx lester! your latest update is hugely helpful!
